Fix TypeScript compilation by adding skipLibCheck
The @types/tar@6.1.13 dependency requires AbortSignal which is not
available with lib: ES2019. Adding skipLibCheck: true to tsconfig.json
allows the build to complete by skipping type checking of declaration
files while still checking our source code.

This fixes the npm test failure caused by:
  node_modules/@types/tar/node_modules/minipass/index.d.ts:31:14
  error TS2304: Cannot find name 'AbortSignal'.

Spec-Ref: helix-specs@a55e4a9:000380_test-the-code-in-this-pr